In [1]:
import numpy as np
from utilities import gridding

/home/tumeilsy-mo-10/anaconda3/envs/safe/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
dim_state = 4
state_constraints = np.array([1, 2, 3, 5])

# state_constraints = np.vstack((-1 * state_constraints, \
#                                     state_constraints)).T
state_constraints = np.vstack((-1 * state_constraints, \
                                    np.array([1, 2, 3, 5]))).T

prec = [2, 2 , 2, 3]
grids = gridding(dim_state, state_constraints, prec)

Grid size: 24
Discretization constant (tau): 0.0


In [3]:
np.zeros_like(state_constraints)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [4]:
grids.all_points

array([[-1., -2., -3., -5.],
       [-1., -2., -3.,  0.],
       [-1., -2., -3.,  5.],
       [-1., -2.,  3., -5.],
       [-1., -2.,  3.,  0.],
       [-1., -2.,  3.,  5.],
       [ 1., -2., -3., -5.],
       [ 1., -2., -3.,  0.],
       [ 1., -2., -3.,  5.],
       [ 1., -2.,  3., -5.],
       [ 1., -2.,  3.,  0.],
       [ 1., -2.,  3.,  5.],
       [-1.,  2., -3., -5.],
       [-1.,  2., -3.,  0.],
       [-1.,  2., -3.,  5.],
       [-1.,  2.,  3., -5.],
       [-1.,  2.,  3.,  0.],
       [-1.,  2.,  3.,  5.],
       [ 1.,  2., -3., -5.],
       [ 1.,  2., -3.,  0.],
       [ 1.,  2., -3.,  5.],
       [ 1.,  2.,  3., -5.],
       [ 1.,  2.,  3.,  0.],
       [ 1.,  2.,  3.,  5.]], dtype=float32)

In [5]:
grids.discrete_points

[array([-1.,  1.], dtype=float32),
 array([-2.,  2.], dtype=float32),
 array([-3.,  3.], dtype=float32),
 array([-5.,  0.,  5.], dtype=float32)]

In [6]:

#  [[ 1.         -1.         -0.30000001 -0.2       ]
#  [ 1.         -1.         -0.30000001  0.2       ]
#  [ 1.          1.         -0.30000001 -0.2       ]
#  [ 1.          1.         -0.30000001  0.2       ]
#  [ 1.         -1.         -0.1        -0.2       ]
#  [ 1.         -1.         -0.1         0.2       ]
#  [ 1.          1.         -0.1        -0.2       ]
#  [ 1.          1.         -0.1         0.2       ]]

res = np.array(([ 1.        , -1.        , -0.30000001, -0.2       ],
                [ 1.        , -1.        , -0.30000001,  0.2       ],
       [ 1.        ,  1.        , -0.30000001, -0.2       ],
       [ 1.        ,  1.        , -0.30000001,  0.2       ],
       [ 1.        , -1.        , -0.1       , -0.2       ],
       [ 1.        , -1.        , -0.1       ,  0.2       ],
       [ 1.        ,  1.        , -0.1       , -0.2       ],
       [ 1.        ,  1.        , -0.1       ,  0.2       ]))

In [7]:
res

array([[ 1.        , -1.        , -0.30000001, -0.2       ],
       [ 1.        , -1.        , -0.30000001,  0.2       ],
       [ 1.        ,  1.        , -0.30000001, -0.2       ],
       [ 1.        ,  1.        , -0.30000001,  0.2       ],
       [ 1.        , -1.        , -0.1       , -0.2       ],
       [ 1.        , -1.        , -0.1       ,  0.2       ],
       [ 1.        ,  1.        , -0.1       , -0.2       ],
       [ 1.        ,  1.        , -0.1       ,  0.2       ]])

In [8]:
# reverse the order of the rows
res_reverse = res[::-1]
res_reverse

array([[ 1.        ,  1.        , -0.1       ,  0.2       ],
       [ 1.        ,  1.        , -0.1       , -0.2       ],
       [ 1.        , -1.        , -0.1       ,  0.2       ],
       [ 1.        , -1.        , -0.1       , -0.2       ],
       [ 1.        ,  1.        , -0.30000001,  0.2       ],
       [ 1.        ,  1.        , -0.30000001, -0.2       ],
       [ 1.        , -1.        , -0.30000001,  0.2       ],
       [ 1.        , -1.        , -0.30000001, -0.2       ]])

In [9]:
# flip the sign from the second to the last columns
res_reverse[:, 1:] = -res_reverse[:, 1:]
res_reverse

array([[ 1.        , -1.        ,  0.1       , -0.2       ],
       [ 1.        , -1.        ,  0.1       ,  0.2       ],
       [ 1.        ,  1.        ,  0.1       , -0.2       ],
       [ 1.        ,  1.        ,  0.1       ,  0.2       ],
       [ 1.        , -1.        ,  0.30000001, -0.2       ],
       [ 1.        , -1.        ,  0.30000001,  0.2       ],
       [ 1.        ,  1.        ,  0.30000001, -0.2       ],
       [ 1.        ,  1.        ,  0.30000001,  0.2       ]])

In [10]:
# concatenate the two arrays
roa = np.concatenate((res, res_reverse), axis=0)
roa

array([[ 1.        ,  1.        ,  0.30000001,  0.2       ],
       [ 1.        ,  1.        ,  0.30000001, -0.2       ],
       [ 1.        , -1.        ,  0.30000001,  0.2       ],
       [ 1.        , -1.        ,  0.30000001, -0.2       ],
       [ 1.        ,  1.        ,  0.1       ,  0.2       ],
       [ 1.        ,  1.        ,  0.1       , -0.2       ],
       [ 1.        , -1.        ,  0.1       ,  0.2       ],
       [ 1.        , -1.        ,  0.1       , -0.2       ],
       [ 1.        , -1.        ,  0.1       , -0.2       ],
       [ 1.        , -1.        ,  0.1       ,  0.2       ],
       [ 1.        ,  1.        ,  0.1       , -0.2       ],
       [ 1.        ,  1.        ,  0.1       ,  0.2       ],
       [ 1.        , -1.        ,  0.30000001, -0.2       ],
       [ 1.        , -1.        ,  0.30000001,  0.2       ],
       [ 1.        ,  1.        ,  0.30000001, -0.2       ],
       [ 1.        ,  1.        ,  0.30000001,  0.2       ]])

In [11]:
True + False

1